import React from "react";
import { Helmet } from "react-helmet";
import "../../styles/pages.css";

function AboutUs() {
  return (
    <div>
      <Helmet>
        <title>About Us</title>
      </Helmet>
      <div className="paragraphContainer">
        <h1>About Us</h1>
        <img 
          src="https://www.charactercabinets.com.au/wp-content/uploads/cc-logo.svg" 
          alt="CharacterLogo"                            
          height= "150"
          width="150">
        </img>
        <img 
          src="https://www.stonewithcharacter.com.au/wp-content/uploads/SwC-logo-white-colour.svg" 
          alt="CharacterLogo"                            
          height= "200"
          width="200">
        </img>
        <p>
        With over 35 years combined experience in the West Australian housing and renovation scene, 
        Character Cabinets and Stone with Character have become trusted suppliers and building partners. 
        Our clients are our priority. We have built our business on the values of honesty and integrity. 
        Much of our work is generated by referrals from our previous customers or repeat clients who have 
        purchased a new home.
        </p>
        <p>
        We use materials from Perth’s leading suppliers to ensure the best quality for our customers. 
        Character Cabinets and Stone with Character have proven to be leading suppliers to many trade businesses. 
        Most of our builders have grown their business with us over this period and continue their loyalty towards us.
        </p>
      </div>
    </div>
  );
}

export default AboutUs;
