[
  {
    "Colour": "Shannon Oak",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "162",
    "ProductCode": 8226,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 120
  },
  {
    "Colour": "Classic White",
    "Finish": "Ashgrain",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "33.3",
    "ProductCode": 8323,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E173",
    "QuantityInStock": 45
  },
  {
    "Colour": "New Antique White",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "36",
    "ProductCode": 11007,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E119",
    "QuantityInStock": 50
  },
  {
    "Colour": "New Antique White",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 11007,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E130",
    "QuantityInStock": 100
  },
  {
    "Colour": "New Antique White",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 11007,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E190",
    "QuantityInStock": 100
  },
  {
    "Colour": "New Antique White",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 11007,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E193",
    "QuantityInStock": 100
  },
  {
    "Colour": "Gesso Lini",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "14.4",
    "ProductCode": 11075,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E25",
    "QuantityInStock": 20
  },
  {
    "Colour": "Marina Grey",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "57.6",
    "ProductCode": 12675,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E114",
    "QuantityInStock": 80
  },
  {
    "Colour": "Moss Grey",
    "Finish": "Matt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "22.8",
    "ProductCode": 17704,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E26",
    "QuantityInStock": 20
  },
  {
    "Colour": "Tuross Oak",
    "Finish": "Matt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "26.22",
    "ProductCode": 17722,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E6",
    "QuantityInStock": 23
  },
  {
    "Colour": "Black",
    "Finish": "Gloss",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "33.83",
    "ProductCode": 17727,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E98",
    "QuantityInStock": 17
  },
  {
    "Colour": "Classic White",
    "Finish": "Ashgrain",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "18.24",
    "ProductCode": 17756,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E65",
    "QuantityInStock": 16
  },
  {
    "Colour": "Cavia Lini",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "36.14",
    "ProductCode": 19195,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E111",
    "QuantityInStock": 26
  },
  {
    "Colour": "Cavia Lini",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "95.91",
    "ProductCode": 19195,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E94",
    "QuantityInStock": 69
  },
  {
    "Colour": "European Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "50.4",
    "ProductCode": 19202,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E46",
    "QuantityInStock": 70
  },
  {
    "Colour": "European Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "64.8",
    "ProductCode": 19202,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E39",
    "QuantityInStock": 90
  },
  {
    "Colour": "European Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 19202,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E154",
    "QuantityInStock": 100
  },
  {
    "Colour": "European Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 19202,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E223",
    "QuantityInStock": 100
  },
  {
    "Colour": "European Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "216",
    "ProductCode": 19202,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 300
  },
  {
    "Colour": "White Mist",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "54",
    "ProductCode": 19348,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E8",
    "QuantityInStock": 75
  },
  {
    "Colour": "Stone Grey",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "36",
    "ProductCode": 19379,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E55",
    "QuantityInStock": 50
  },
  {
    "Colour": "Stone Grey",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "42.92",
    "ProductCode": 19379,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E9",
    "QuantityInStock": 58
  },
  {
    "Colour": "White Mist",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 19380,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E188",
    "QuantityInStock": 100
  },
  {
    "Colour": "Soft Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "16.28",
    "ProductCode": 19399,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E27",
    "QuantityInStock": 22
  },
  {
    "Colour": "Polar White",
    "Finish": "Sheen",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "22.2",
    "ProductCode": 19537,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E11",
    "QuantityInStock": 20
  },
  {
    "Colour": "Polar White",
    "Finish": "Sheen",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "22.2",
    "ProductCode": 19537,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E82",
    "QuantityInStock": 20
  },
  {
    "Colour": "Black Wenge",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "25.16",
    "ProductCode": 19545,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E205",
    "QuantityInStock": 34
  },
  {
    "Colour": "Char Oak",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "28.8",
    "ProductCode": 19546,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E28",
    "QuantityInStock": 40
  },
  {
    "Colour": "Char Oak",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 19546,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E188",
    "QuantityInStock": 100
  },
  {
    "Colour": "Tessuto Milan",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "64.8",
    "ProductCode": 19547,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "e12",
    "QuantityInStock": 90
  },
  {
    "Colour": "Marni Lini",
    "Finish": "Finegrain",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "40.2",
    "ProductCode": 20144,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E33",
    "QuantityInStock": 20
  },
  {
    "Colour": "Truffle Lini",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "34.75",
    "ProductCode": 20370,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E143",
    "QuantityInStock": 25
  },
  {
    "Colour": "Cinder",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "36",
    "ProductCode": 20375,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E49",
    "QuantityInStock": 50
  },
  {
    "Colour": "Black Wenge",
    "Finish": "Ravine",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "70.2",
    "ProductCode": 26425,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E226",
    "QuantityInStock": 52
  },
  {
    "Colour": "Soft Walnut",
    "Finish": "Ravine",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "41",
    "ProductCode": 26438,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E230",
    "QuantityInStock": 20
  },
  {
    "Colour": "Soft Walnut",
    "Finish": "Ravine",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "51.25",
    "ProductCode": 26438,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E236",
    "QuantityInStock": 25
  },
  {
    "Colour": "Tessuto Milan",
    "Finish": "Ravine",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "97.2",
    "ProductCode": 26445,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E191",
    "QuantityInStock": 72
  },
  {
    "Colour": "Sepia Oak",
    "Finish": "Ravine",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "39.8",
    "ProductCode": 26450,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 20
  },
  {
    "Colour": "Crisp White",
    "Finish": "Legato",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "72",
    "ProductCode": 26773,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 100
  },
  {
    "Colour": "Silk",
    "Finish": "Legato",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "61.42",
    "ProductCode": 26776,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E5",
    "QuantityInStock": 83
  },
  {
    "Colour": "Bone White",
    "Finish": "Legato",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "21.9",
    "ProductCode": 26790,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E43",
    "QuantityInStock": 15
  },
  {
    "Colour": "Feldspar Shimmer (P)",
    "Finish": "Matt",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "18.5",
    "ProductCode": 27480,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E98",
    "QuantityInStock": 25
  },
  {
    "Colour": "Feldspar Shimmer (P)",
    "Finish": "Matt",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "29.6",
    "ProductCode": 27480,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E45",
    "QuantityInStock": 40
  },
  {
    "Colour": "Riga Ember",
    "Finish": "Finegrain",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "111.2",
    "ProductCode": 27710,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E150",
    "QuantityInStock": 80
  },
  {
    "Colour": "Riga Ember",
    "Finish": "Finegrain",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "118.15",
    "ProductCode": 27710,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E138",
    "QuantityInStock": 85
  },
  {
    "Colour": "Riga Salt",
    "Finish": "Finegrain",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "82.35",
    "ProductCode": 27714,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E116",
    "QuantityInStock": 61
  },
  {
    "Colour": "Combat Teak (P)",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "14.4",
    "ProductCode": 42650,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E159",
    "QuantityInStock": 20
  },
  {
    "Colour": "Highland Cherry",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "44.64",
    "ProductCode": 42652,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E161",
    "QuantityInStock": 62
  },
  {
    "Colour": "Jamaican Walnut",
    "Finish": "Matt",
    "Length": 20,
    "Width": 21,
    "Thickness": 1,
    "price": "17.1",
    "ProductCode": 43726,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E19",
    "QuantityInStock": 15
  },
  {
    "Colour": "White Cotton",
    "Finish": "Matt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "29.64",
    "ProductCode": 43738,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E16",
    "QuantityInStock": 26
  },
  {
    "Colour": "Husk (P)",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "37",
    "ProductCode": 43748,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E175",
    "QuantityInStock": 50
  },
  {
    "Colour": "Jamaican Walnut",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "21.6",
    "ProductCode": 43751,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E47",
    "QuantityInStock": 30
  },
  {
    "Colour": "Titanium",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "12.96",
    "ProductCode": 43757,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E1",
    "QuantityInStock": 18
  },
  {
    "Colour": "New Ultra White",
    "Finish": "Gloss",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "39.8",
    "ProductCode": 44528,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 20
  },
  {
    "Colour": "Soft Grey",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 23,
    "Thickness": 1,
    "price": "309",
    "ProductCode": 45758,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 100
  },
  {
    "Colour": "Anthracite Metallic",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "61.56",
    "ProductCode": 45765,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E24",
    "QuantityInStock": 36
  },
  {
    "Colour": "Premiere Metallic",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "114.57",
    "ProductCode": 45787,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E10",
    "QuantityInStock": 67
  },
  {
    "Colour": "Soft Grey",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 23,
    "Thickness": 1,
    "price": "117",
    "ProductCode": 45791,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E126",
    "QuantityInStock": 100
  },
  {
    "Colour": "Superior White",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "87",
    "ProductCode": 45793,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E233",
    "QuantityInStock": 75
  },
  {
    "Colour": "Notaio Walnut",
    "Finish": "Ravine",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "121.5",
    "ProductCode": 46458,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E150",
    "QuantityInStock": 90
  },
  {
    "Colour": "Blossom White",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "18.5",
    "ProductCode": 46590,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E191",
    "QuantityInStock": 25
  },
  {
    "Colour": "Blossom White",
    "Finish": "Sheen",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "23.68",
    "ProductCode": 46590,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E217",
    "QuantityInStock": 32
  },
  {
    "Colour": "Casentino Beech",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "82.16",
    "ProductCode": 46595,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E94",
    "QuantityInStock": 79
  },
  {
    "Colour": "Black",
    "Finish": "Venette",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "51.1",
    "ProductCode": 46661,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E225",
    "QuantityInStock": 35
  },
  {
    "Colour": "Black",
    "Finish": "Venette",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "52.56",
    "ProductCode": 46661,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E203",
    "QuantityInStock": 36
  },
  {
    "Colour": "Black",
    "Finish": "Venette",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "97.82",
    "ProductCode": 46661,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "146",
    "QuantityInStock": 67
  },
  {
    "Colour": "Black",
    "Finish": "Venette",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "100.74",
    "ProductCode": 46661,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E31",
    "QuantityInStock": 69
  },
  {
    "Colour": "Black",
    "Finish": "Venette",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "146",
    "ProductCode": 46661,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E106",
    "QuantityInStock": 100
  },
  {
    "Colour": "Cinder",
    "Finish": "Venette",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "100.11",
    "ProductCode": 46662,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "e7",
    "QuantityInStock": 71
  },
  {
    "Colour": "Notaio Walnut",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "57.2",
    "ProductCode": 46764,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E87",
    "QuantityInStock": 55
  },
  {
    "Colour": "Estella Oak",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "58.58",
    "ProductCode": 46776,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "194",
    "QuantityInStock": 58
  },
  {
    "Colour": "Prime Oak",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "27.4",
    "ProductCode": 46800,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E179",
    "QuantityInStock": 20
  },
  {
    "Colour": "Coastal Oak",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "53.2",
    "ProductCode": 46803,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E24",
    "QuantityInStock": 40
  },
  {
    "Colour": "Bottega Oak",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "26.6",
    "ProductCode": 46805,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E26",
    "QuantityInStock": 20
  },
  {
    "Colour": "Bottega Oak",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "27.93",
    "ProductCode": 46805,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E19",
    "QuantityInStock": 21
  },
  {
    "Colour": "Platinum Leaf",
    "Finish": "Matt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "27.4",
    "ProductCode": 46808,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E23",
    "QuantityInStock": 20
  },
  {
    "Colour": "Platinum Leaf",
    "Finish": "Matt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "27.4",
    "ProductCode": 46808,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E24",
    "QuantityInStock": 20
  },
  {
    "Colour": "Ultra White",
    "Finish": "Venette",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "26.28",
    "ProductCode": 48358,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E197",
    "QuantityInStock": 18
  },
  {
    "Colour": "Black",
    "Finish": "Ultramatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "36",
    "ProductCode": 48571,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E176",
    "QuantityInStock": 30
  },
  {
    "Colour": "Black",
    "Finish": "Ultramatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "120",
    "ProductCode": 48571,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E208",
    "QuantityInStock": 100
  },
  {
    "Colour": "White",
    "Finish": "Ultramatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "76.8",
    "ProductCode": 48573,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E18",
    "QuantityInStock": 64
  },
  {
    "Colour": "White",
    "Finish": "Ultramatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "93.6",
    "ProductCode": 48573,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E8",
    "QuantityInStock": 78
  },
  {
    "Colour": "Oxford",
    "Finish": "Venette",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "33.58",
    "ProductCode": 48993,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E104",
    "QuantityInStock": 23
  },
  {
    "Colour": "Oxford",
    "Finish": "Venette",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "138.7",
    "ProductCode": 48993,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E104",
    "QuantityInStock": 95
  },
  {
    "Colour": "Perugian Walnut",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "21.21",
    "ProductCode": 49010,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E87",
    "QuantityInStock": 21
  },
  {
    "Colour": "Rojo Walnut",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "27.4",
    "ProductCode": 50303,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E3",
    "QuantityInStock": 20
  },
  {
    "Colour": "Avion Grey",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "18.5",
    "ProductCode": 50509,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E95",
    "QuantityInStock": 25
  },
  {
    "Colour": "Maison Oak",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "25.16",
    "ProductCode": 50538,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E78",
    "QuantityInStock": 34
  },
  {
    "Colour": "Ferro",
    "Finish": "Matt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "28.08",
    "ProductCode": 50782,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E144",
    "QuantityInStock": 39
  },
  {
    "Colour": "Blossom White",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "20.55",
    "ProductCode": 51165,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E181",
    "QuantityInStock": 15
  },
  {
    "Colour": "Blossom White",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "73.84",
    "ProductCode": 51180,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E48",
    "QuantityInStock": 71
  },
  {
    "Colour": "Serene",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "55.12",
    "ProductCode": 51182,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E124",
    "QuantityInStock": 53
  },
  {
    "Colour": "Silk",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "88.4",
    "ProductCode": 51183,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E18",
    "QuantityInStock": 85
  },
  {
    "Colour": "Pallido",
    "Finish": "Smooth",
    "Length": 20,
    "Width": 21,
    "Thickness": 1,
    "price": "0",
    "ProductCode": 51431,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E252",
    "QuantityInStock": 20
  },
  {
    "Colour": "Black Ply",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "20.55",
    "ProductCode": 52643,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E22",
    "QuantityInStock": 15
  },
  {
    "Colour": "Black Ply",
    "Finish": "Woodmatt",
    "Length": 20,
    "Width": 22,
    "Thickness": 1,
    "price": "27.4",
    "ProductCode": 52643,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E155",
    "QuantityInStock": 20
  },
  {
    "Colour": "Plantation Ash",
    "Finish": "Woodmatt",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "36.4",
    "ProductCode": 52688,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[5]._id",
    "BayLocation": "E5",
    "QuantityInStock": 35
  },
  {
    "Colour": "Black",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "44.53",
    "ProductCode": 163375,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E63",
    "QuantityInStock": 61
  },
  {
    "Colour": "Warm White",
    "Finish": "Satin",
    "Length": 100,
    "Width": 29,
    "Thickness": 2,
    "price": "686.4",
    "ProductCode": 435167,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "",
    "QuantityInStock": 660
  },
  {
    "Colour": "Antique Wiluna White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "9.24",
    "ProductCode": 813218,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E4",
    "QuantityInStock": 28
  },
  {
    "Colour": "Antique Wiluna White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "14.85",
    "ProductCode": 813218,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E5",
    "QuantityInStock": 45
  },
  {
    "Colour": "New Graphite",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "46.06",
    "ProductCode": 846060,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E206",
    "QuantityInStock": 47
  },
  {
    "Colour": "Platinum Micro",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "74",
    "ProductCode": 846151,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E126",
    "QuantityInStock": 100
  },
  {
    "Colour": "Brushed Silver",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "17.46",
    "ProductCode": 848497,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E119",
    "QuantityInStock": 18
  },
  {
    "Colour": "Char Blue",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "11.1",
    "ProductCode": 848499,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E1",
    "QuantityInStock": 15
  },
  {
    "Colour": "Silver Strata",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "21.34",
    "ProductCode": 848536,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E71",
    "QuantityInStock": 22
  },
  {
    "Colour": "Dansk Maple",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "42.32",
    "ProductCode": 853032,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E183",
    "QuantityInStock": 92
  },
  {
    "Colour": "Polar White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "939.3",
    "ProductCode": 857214,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "Stock",
    "QuantityInStock": 3030
  },
  {
    "Colour": "New Antique White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21.12",
    "ProductCode": 857340,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E26",
    "QuantityInStock": 64
  },
  {
    "Colour": "Fossil",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "25.5",
    "ProductCode": 857826,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E81",
    "QuantityInStock": 85
  },
  {
    "Colour": "Fossil",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "30",
    "ProductCode": 857826,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E105",
    "QuantityInStock": 100
  },
  {
    "Colour": "Moleskin",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "31.35",
    "ProductCode": 862673,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E164",
    "QuantityInStock": 95
  },
  {
    "Colour": "Velveteen",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "5.28",
    "ProductCode": 874984,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E63",
    "QuantityInStock": 16
  },
  {
    "Colour": "Licorice Linea",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "40.8",
    "ProductCode": 877667,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E4",
    "QuantityInStock": 85
  },
  {
    "Colour": "Parchment",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "16.2",
    "ProductCode": 878726,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E8",
    "QuantityInStock": 15
  },
  {
    "Colour": "Eggshell",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "12.6",
    "ProductCode": 883037,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "e122",
    "QuantityInStock": 42
  },
  {
    "Colour": "New Graphite",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "15",
    "ProductCode": 884946,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E218",
    "QuantityInStock": 30
  },
  {
    "Colour": "Milkwood",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "50",
    "ProductCode": 885921,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E88",
    "QuantityInStock": 100
  },
  {
    "Colour": "Zincworks",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "42.32",
    "ProductCode": 885933,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E10",
    "QuantityInStock": 92
  },
  {
    "Colour": "Streetlight",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "23.76",
    "ProductCode": 887046,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E197",
    "QuantityInStock": 72
  },
  {
    "Colour": "Cappuccino",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "14.85",
    "ProductCode": 887267,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E169",
    "QuantityInStock": 45
  },
  {
    "Colour": "Cappuccino",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "16.17",
    "ProductCode": 887267,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E205",
    "QuantityInStock": 49
  },
  {
    "Colour": "Prestige Walnut",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "19.8",
    "ProductCode": 906214,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E42",
    "QuantityInStock": 45
  },
  {
    "Colour": "Doe Skin",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "15.25",
    "ProductCode": 906220,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E235",
    "QuantityInStock": 25
  },
  {
    "Colour": "Antler",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.08",
    "ProductCode": 906221,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E212",
    "QuantityInStock": 18
  },
  {
    "Colour": "Fini Blonde",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "27.5",
    "ProductCode": 906231,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E12",
    "QuantityInStock": 25
  },
  {
    "Colour": "Fini Blonde",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "27.5",
    "ProductCode": 906231,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E4",
    "QuantityInStock": 25
  },
  {
    "Colour": "Fini Blonde",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "55",
    "ProductCode": 906231,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E13",
    "QuantityInStock": 50
  },
  {
    "Colour": "Gentle Beige",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "33",
    "ProductCode": 909149,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E165",
    "QuantityInStock": 100
  },
  {
    "Colour": "Asphalt",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "11.22",
    "ProductCode": 909160,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E9",
    "QuantityInStock": 33
  },
  {
    "Colour": "Asphalt",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "23.8",
    "ProductCode": 909160,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E138",
    "QuantityInStock": 70
  },
  {
    "Colour": "Golden Beech",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "49.82",
    "ProductCode": 909161,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 106
  },
  {
    "Colour": "Indian Sage",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "9.61",
    "ProductCode": 910186,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E175",
    "QuantityInStock": 31
  },
  {
    "Colour": "Ink",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21.45",
    "ProductCode": 910194,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E127",
    "QuantityInStock": 65
  },
  {
    "Colour": "Ink",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "33",
    "ProductCode": 910194,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E133",
    "QuantityInStock": 100
  },
  {
    "Colour": "Antique Wiluna White",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "14",
    "ProductCode": 910198,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E4",
    "QuantityInStock": 25
  },
  {
    "Colour": "Deep Anthracite",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "15.25",
    "ProductCode": 910200,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E161",
    "QuantityInStock": 25
  },
  {
    "Colour": "Graphite",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "15.25",
    "ProductCode": 910211,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E34",
    "QuantityInStock": 25
  },
  {
    "Colour": "Storm",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "12.16",
    "ProductCode": 910218,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E26",
    "QuantityInStock": 19
  },
  {
    "Colour": "Streetlight",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "15.86",
    "ProductCode": 910219,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E17",
    "QuantityInStock": 26
  },
  {
    "Colour": "Brushed Silver",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "30",
    "ProductCode": 910225,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E211",
    "QuantityInStock": 60
  },
  {
    "Colour": "Lemon Tree",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "22",
    "ProductCode": 910243,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E92",
    "QuantityInStock": 20
  },
  {
    "Colour": "Rock Salt",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "29.75",
    "ProductCode": 910247,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E120",
    "QuantityInStock": 25
  },
  {
    "Colour": "Basalt",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "47",
    "ProductCode": 914759,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E114",
    "QuantityInStock": 100
  },
  {
    "Colour": "New Antique White",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "14",
    "ProductCode": 916607,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E15",
    "QuantityInStock": 20
  },
  {
    "Colour": "Silver Grey",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.95",
    "ProductCode": 916654,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E73",
    "QuantityInStock": 15
  },
  {
    "Colour": "Silver Grey",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "18.25",
    "ProductCode": 916654,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E53",
    "QuantityInStock": 25
  },
  {
    "Colour": "Select Beech",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "38.5",
    "ProductCode": 916685,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E21",
    "QuantityInStock": 25
  },
  {
    "Colour": "New Graphite",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "35.5",
    "ProductCode": 916697,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E59",
    "QuantityInStock": 25
  },
  {
    "Colour": "Milkwood",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "29.26",
    "ProductCode": 916711,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E78",
    "QuantityInStock": 19
  },
  {
    "Colour": "Rock Maple",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "35.5",
    "ProductCode": 916720,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E52",
    "QuantityInStock": 25
  },
  {
    "Colour": "Black",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "19.89",
    "ProductCode": 932941,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E209",
    "QuantityInStock": 17
  },
  {
    "Colour": "Black",
    "Finish": "Matt",
    "Length": 100,
    "Width": 23,
    "Thickness": 1,
    "price": "141.68",
    "ProductCode": 933324,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E21",
    "QuantityInStock": 88
  },
  {
    "Colour": "Bliss Cinder",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "16.5",
    "ProductCode": 934561,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E58",
    "QuantityInStock": 15
  },
  {
    "Colour": "Bliss Cinder",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "19.89",
    "ProductCode": 934579,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E43",
    "QuantityInStock": 39
  },
  {
    "Colour": "Sarsen Grey",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "27",
    "ProductCode": 936427,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E129",
    "QuantityInStock": 25
  },
  {
    "Colour": "Warm White",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "22.77",
    "ProductCode": 939757,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E214",
    "QuantityInStock": 23
  },
  {
    "Colour": "Refined Oak",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "46.46",
    "ProductCode": 939768,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E148",
    "QuantityInStock": 46
  },
  {
    "Colour": "Snowdrift",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "1,169.20",
    "ProductCode": 939769,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "Stock",
    "QuantityInStock": 3160
  },
  {
    "Colour": "Alpaca",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "7.5",
    "ProductCode": 945061,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E131",
    "QuantityInStock": 25
  },
  {
    "Colour": "Avignon Walnut",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "37.5",
    "ProductCode": 945062,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E164",
    "QuantityInStock": 75
  },
  {
    "Colour": "Moose",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "69.92",
    "ProductCode": 945073,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E150",
    "QuantityInStock": 152
  },
  {
    "Colour": "Baye",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.2",
    "ProductCode": 945105,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E61",
    "QuantityInStock": 15
  },
  {
    "Colour": "Streetlight",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "33.66",
    "ProductCode": 954701,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E22",
    "QuantityInStock": 34
  },
  {
    "Colour": "Streetlight",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "99",
    "ProductCode": 954701,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E146",
    "QuantityInStock": 100
  },
  {
    "Colour": "Hotham Oak",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "32.25",
    "ProductCode": 954709,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 25
  },
  {
    "Colour": "Mulga",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "16.34",
    "ProductCode": 954716,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E215",
    "QuantityInStock": 19
  },
  {
    "Colour": "Mulga",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "21.5",
    "ProductCode": 954716,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E71",
    "QuantityInStock": 25
  },
  {
    "Colour": "Silver Strata",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "32.25",
    "ProductCode": 954719,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E64",
    "QuantityInStock": 25
  },
  {
    "Colour": "Silver Strata",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "32.25",
    "ProductCode": 954719,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E73",
    "QuantityInStock": 25
  },
  {
    "Colour": "Whitewashed Oak",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "46.86",
    "ProductCode": 961203,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E23",
    "QuantityInStock": 33
  },
  {
    "Colour": "Infinity",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21",
    "ProductCode": 961224,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E40",
    "QuantityInStock": 70
  },
  {
    "Colour": "Alaskan",
    "Finish": "Nuance",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "23.25",
    "ProductCode": 962228,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E11",
    "QuantityInStock": 15
  },
  {
    "Colour": "Blackened Linewood",
    "Finish": "Nuance",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "38.4",
    "ProductCode": 962234,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E71",
    "QuantityInStock": 60
  },
  {
    "Colour": "Blackened Linewood",
    "Finish": "Nuance",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "56.32",
    "ProductCode": 962234,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E21",
    "QuantityInStock": 88
  },
  {
    "Colour": "Burnished Wood",
    "Finish": "Nuance",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "23.25",
    "ProductCode": 962240,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E5",
    "QuantityInStock": 15
  },
  {
    "Colour": "Lustrous Elm",
    "Finish": "Nuance",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "40.2",
    "ProductCode": 962284,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E79",
    "QuantityInStock": 60
  },
  {
    "Colour": "Polar White",
    "Finish": "Nuance",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "37.2",
    "ProductCode": 962322,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E6",
    "QuantityInStock": 30
  },
  {
    "Colour": "Smoky Sapelle",
    "Finish": "Nuance",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "23.25",
    "ProductCode": 962338,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E77",
    "QuantityInStock": 15
  },
  {
    "Colour": "Whitewashed Oak",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "60.8",
    "ProductCode": 962486,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E5",
    "QuantityInStock": 95
  },
  {
    "Colour": "Pearl Grey",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "13.6",
    "ProductCode": 963584,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E155",
    "QuantityInStock": 20
  },
  {
    "Colour": "Alaskan",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "38.22",
    "ProductCode": 966235,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E206",
    "QuantityInStock": 39
  },
  {
    "Colour": "Avignon Walnut",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "57.6",
    "ProductCode": 967561,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E216",
    "QuantityInStock": 60
  },
  {
    "Colour": "Crystal White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "66",
    "ProductCode": 967849,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E199",
    "QuantityInStock": 200
  },
  {
    "Colour": "Sarum Grey",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "14",
    "ProductCode": 967990,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E31",
    "QuantityInStock": 25
  },
  {
    "Colour": "Finesse Taupe",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "16.8",
    "ProductCode": 967995,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E32",
    "QuantityInStock": 15
  },
  {
    "Colour": "Ash Woodline",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "17.85",
    "ProductCode": 968000,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E41",
    "QuantityInStock": 15
  },
  {
    "Colour": "Brushed Nickel",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "41.5",
    "ProductCode": 968010,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E162",
    "QuantityInStock": 83
  },
  {
    "Colour": "Finesse Taupe",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "9.4",
    "ProductCode": 968014,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E115",
    "QuantityInStock": 20
  },
  {
    "Colour": "Charred Woodline",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "22.5",
    "ProductCode": 968020,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E10",
    "QuantityInStock": 45
  },
  {
    "Colour": "Charred Woodline",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "22.5",
    "ProductCode": 968020,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E129",
    "QuantityInStock": 45
  },
  {
    "Colour": "Cuban Wood",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "32.5",
    "ProductCode": 968024,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E10",
    "QuantityInStock": 65
  },
  {
    "Colour": "Malibu",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "18.5",
    "ProductCode": 968026,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E36",
    "QuantityInStock": 25
  },
  {
    "Colour": "Sarum Strand",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "14.55",
    "ProductCode": 968036,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E158",
    "QuantityInStock": 15
  },
  {
    "Colour": "Finesse Taupe",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "35.52",
    "ProductCode": 968052,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E221",
    "QuantityInStock": 37
  },
  {
    "Colour": "Cuban Wood",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "32.01",
    "ProductCode": 968063,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E182",
    "QuantityInStock": 33
  },
  {
    "Colour": "Oyster Linea",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "53.04",
    "ProductCode": 972649,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E88",
    "QuantityInStock": 52
  },
  {
    "Colour": "Black",
    "Finish": "Nuance",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "69",
    "ProductCode": 972996,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E169",
    "QuantityInStock": 75
  },
  {
    "Colour": "Cuban Wood",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "96",
    "ProductCode": 975811,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E68",
    "QuantityInStock": 100
  },
  {
    "Colour": "Fox",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21.12",
    "ProductCode": 977190,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E68",
    "QuantityInStock": 64
  },
  {
    "Colour": "Super White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "31.04",
    "ProductCode": 977193,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E21",
    "QuantityInStock": 97
  },
  {
    "Colour": "Tornado",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "6.6",
    "ProductCode": 977194,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E7",
    "QuantityInStock": 22
  },
  {
    "Colour": "Clay Textile",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "30",
    "ProductCode": 977221,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E44",
    "QuantityInStock": 60
  },
  {
    "Colour": "Concrete Formwood",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "23",
    "ProductCode": 977222,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E125",
    "QuantityInStock": 50
  },
  {
    "Colour": "Concrete Formwood",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "40.02",
    "ProductCode": 977222,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E15",
    "QuantityInStock": 87
  },
  {
    "Colour": "Natural Walnut",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "16.1",
    "ProductCode": 977232,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E3",
    "QuantityInStock": 35
  },
  {
    "Colour": "Honey Elm",
    "Finish": "Satin",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "21.3",
    "ProductCode": 977271,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E48",
    "QuantityInStock": 15
  },
  {
    "Colour": "Natural Walnut",
    "Finish": "Satin",
    "Length": 100,
    "Width": 22,
    "Thickness": 2,
    "price": "37.24",
    "ProductCode": 977307,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E112",
    "QuantityInStock": 38
  },
  {
    "Colour": "Natural Walnut",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "16.66",
    "ProductCode": 977342,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E140",
    "QuantityInStock": 17
  },
  {
    "Colour": "Rural Oak",
    "Finish": "Satin",
    "Length": 25,
    "Width": 22,
    "Thickness": 2,
    "price": "24.5",
    "ProductCode": 977343,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E8",
    "QuantityInStock": 25
  },
  {
    "Colour": "Classic Oak",
    "Finish": "Nuance",
    "Length": 100,
    "Width": 29,
    "Thickness": 2,
    "price": "151.2",
    "ProductCode": 984215,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "STOCK PALLET",
    "QuantityInStock": 80
  },
  {
    "Colour": "Classic Oak",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "37.25",
    "ProductCode": 984220,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E142",
    "QuantityInStock": 25
  },
  {
    "Colour": "Classic Oak",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "37.25",
    "ProductCode": 984220,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E171",
    "QuantityInStock": 25
  },
  {
    "Colour": "Lava Grey",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "9.6",
    "ProductCode": 984685,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E154",
    "QuantityInStock": 32
  },
  {
    "Colour": "Smoked Birchply",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "22.35",
    "ProductCode": 985620,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E167",
    "QuantityInStock": 15
  },
  {
    "Colour": "Smoked Birchply",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "22.35",
    "ProductCode": 985620,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E77",
    "QuantityInStock": 15
  },
  {
    "Colour": "Spinifex",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "13.6",
    "ProductCode": 985621,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E128",
    "QuantityInStock": 20
  },
  {
    "Colour": "Possum",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "13.8",
    "ProductCode": 985623,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E151",
    "QuantityInStock": 20
  },
  {
    "Colour": "Seed",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "10.85",
    "ProductCode": 985628,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E117",
    "QuantityInStock": 35
  },
  {
    "Colour": "Seed",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "31",
    "ProductCode": 985628,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "EPALLET",
    "QuantityInStock": 100
  },
  {
    "Colour": "Rural Oak",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "29.26",
    "ProductCode": 985691,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E226",
    "QuantityInStock": 19
  },
  {
    "Colour": "Calm White",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "11.68",
    "ProductCode": 985974,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E214",
    "QuantityInStock": 16
  },
  {
    "Colour": "Calm White",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "12.41",
    "ProductCode": 985974,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E159",
    "QuantityInStock": 17
  },
  {
    "Colour": "Calm White",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "18.25",
    "ProductCode": 985974,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E172",
    "QuantityInStock": 25
  },
  {
    "Colour": "Surf",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "31.5",
    "ProductCode": 985977,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E118",
    "QuantityInStock": 45
  },
  {
    "Colour": "Calm White",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "20.79",
    "ProductCode": 985985,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E54",
    "QuantityInStock": 63
  },
  {
    "Colour": "Stormcloud",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21.12",
    "ProductCode": 985986,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E44",
    "QuantityInStock": 64
  },
  {
    "Colour": "Just Lilac",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.95",
    "ProductCode": 986024,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E232",
    "QuantityInStock": 15
  },
  {
    "Colour": "Green Slate",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "12.24",
    "ProductCode": 986027,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E99",
    "QuantityInStock": 18
  },
  {
    "Colour": "Enamel",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.5",
    "ProductCode": 986030,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E33",
    "QuantityInStock": 15
  },
  {
    "Colour": "Alpine Mist",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "17.5",
    "ProductCode": 986031,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E22",
    "QuantityInStock": 25
  },
  {
    "Colour": "White Painted Wood",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "22.35",
    "ProductCode": 986036,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E158",
    "QuantityInStock": 15
  },
  {
    "Colour": "White Painted Wood",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "38.74",
    "ProductCode": 986036,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E19",
    "QuantityInStock": 26
  },
  {
    "Colour": "Green Slate",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "12.16",
    "ProductCode": 986042,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E46",
    "QuantityInStock": 38
  },
  {
    "Colour": "Denim",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21.35",
    "ProductCode": 986043,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E135",
    "QuantityInStock": 61
  },
  {
    "Colour": "Alpine Mist",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "24.75",
    "ProductCode": 986046,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E29",
    "QuantityInStock": 75
  },
  {
    "Colour": "Terril",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "12.21",
    "ProductCode": 986048,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E201",
    "QuantityInStock": 37
  },
  {
    "Colour": "White Painted Wood",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "40",
    "ProductCode": 986051,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E102",
    "QuantityInStock": 80
  },
  {
    "Colour": "Aged Walnut",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "20.4",
    "ProductCode": 986347,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E62",
    "QuantityInStock": 15
  },
  {
    "Colour": "Bleached Elm",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "21.62",
    "ProductCode": 986360,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "e121",
    "QuantityInStock": 47
  },
  {
    "Colour": "Jarrah Legno",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "22.5",
    "ProductCode": 986361,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E84",
    "QuantityInStock": 45
  },
  {
    "Colour": "Jarrah Legno",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "24.5",
    "ProductCode": 986361,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E103",
    "QuantityInStock": 49
  },
  {
    "Colour": "Natural Teak",
    "Finish": "Nuance",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "75.5",
    "ProductCode": 986365,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "PALLET/E17",
    "QuantityInStock": 50
  },
  {
    "Colour": "Sublime Teak",
    "Finish": "Chalk",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "40.75",
    "ProductCode": 988333,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E2",
    "QuantityInStock": 25
  },
  {
    "Colour": "Sublime Teak",
    "Finish": "Chalk",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "40.75",
    "ProductCode": 988333,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E58",
    "QuantityInStock": 25
  },
  {
    "Colour": "Blackened Legno",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "24.79",
    "ProductCode": 988334,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E38",
    "QuantityInStock": 37
  },
  {
    "Colour": "Natural Walnut",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "23.5",
    "ProductCode": 988338,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E82",
    "QuantityInStock": 50
  },
  {
    "Colour": "Rural Oak",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "16.1",
    "ProductCode": 988340,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E92",
    "QuantityInStock": 35
  },
  {
    "Colour": "Rural Oak",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "46",
    "ProductCode": 988340,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E228",
    "QuantityInStock": 100
  },
  {
    "Colour": "Sublime Teak",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "47.61",
    "ProductCode": 988341,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E157",
    "QuantityInStock": 69
  },
  {
    "Colour": "French Navy",
    "Finish": "Matte",
    "Length": 25,
    "Width": 23,
    "Thickness": 1,
    "price": "48.25",
    "ProductCode": 988400,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E26",
    "QuantityInStock": 25
  },
  {
    "Colour": "Aged Walnut",
    "Finish": "Chalk",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "33.22",
    "ProductCode": 988641,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E57",
    "QuantityInStock": 22
  },
  {
    "Colour": "Artisan Beamwood",
    "Finish": "Chalk",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "26.35",
    "ProductCode": 988643,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E10",
    "QuantityInStock": 17
  },
  {
    "Colour": "Seasoned Planked Elm",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "44.85",
    "ProductCode": 988646,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E29",
    "QuantityInStock": 65
  },
  {
    "Colour": "Black Birchply",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "32.34",
    "ProductCode": 989414,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E25",
    "QuantityInStock": 21
  },
  {
    "Colour": "Elegant Oak",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "25.6",
    "ProductCode": 991585,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E117",
    "QuantityInStock": 40
  },
  {
    "Colour": "Sandy Birch",
    "Finish": "Satin",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "33.12",
    "ProductCode": 991610,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E103",
    "QuantityInStock": 69
  },
  {
    "Colour": "Elegant Oak",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "19.68",
    "ProductCode": 991662,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E11",
    "QuantityInStock": 41
  },
  {
    "Colour": "Deep Sea ",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "13.2",
    "ProductCode": 991696,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E6",
    "QuantityInStock": 40
  },
  {
    "Colour": "Deep Sea ",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "25.41",
    "ProductCode": 991696,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E54",
    "QuantityInStock": 77
  },
  {
    "Colour": "Surf",
    "Finish": "Matt",
    "Length": 100,
    "Width": 23,
    "Thickness": 1,
    "price": "161",
    "ProductCode": 992277,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E202",
    "QuantityInStock": 100
  },
  {
    "Colour": "Terril",
    "Finish": "Matte",
    "Length": 100,
    "Width": 23,
    "Thickness": 1,
    "price": "66.4",
    "ProductCode": 992278,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E30",
    "QuantityInStock": 40
  },
  {
    "Colour": "Oyster Grey New Silk",
    "Finish": "Silk",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "30.1",
    "ProductCode": 992645,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E141",
    "QuantityInStock": 35
  },
  {
    "Colour": "Bluegrass",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.37",
    "ProductCode": 992700,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E2",
    "QuantityInStock": 17
  },
  {
    "Colour": "Planked Urban Oak",
    "Finish": "Chalk",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "27.9",
    "ProductCode": 992703,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E72",
    "QuantityInStock": 18
  },
  {
    "Colour": "Terril",
    "Finish": "Pure Grain",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "24.45",
    "ProductCode": 992710,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E35",
    "QuantityInStock": 15
  },
  {
    "Colour": "Avignon Walnut",
    "Finish": "Chalk",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "38.75",
    "ProductCode": 992778,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E24",
    "QuantityInStock": 25
  },
  {
    "Colour": "Seasoned Oak",
    "Finish": "Chalk",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "26.22",
    "ProductCode": 992795,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E20",
    "QuantityInStock": 38
  },
  {
    "Colour": "Autumn Oak",
    "Finish": "Grain",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "19.55",
    "ProductCode": 992966,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E26",
    "QuantityInStock": 17
  },
  {
    "Colour": "Bodega Oak",
    "Finish": "Grain",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "28.75",
    "ProductCode": 992967,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "",
    "QuantityInStock": 25
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Grain",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "21.85",
    "ProductCode": 992968,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E9",
    "QuantityInStock": 19
  },
  {
    "Colour": "Autumn Oak",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "28.75",
    "ProductCode": 992971,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E85",
    "QuantityInStock": 25
  },
  {
    "Colour": "Tassie Oak",
    "Finish": "Stipple",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "29.75",
    "ProductCode": 992975,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E74",
    "QuantityInStock": 25
  },
  {
    "Colour": "Tassie Oak",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 22,
    "Thickness": 1,
    "price": "33.75",
    "ProductCode": 992978,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E13",
    "QuantityInStock": 25
  },
  {
    "Colour": "Black",
    "Finish": "Grain",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.37",
    "ProductCode": 992979,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E209",
    "QuantityInStock": 17
  },
  {
    "Colour": "Warm White",
    "Finish": "Grain",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "351.9",
    "ProductCode": 992981,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E20",
    "QuantityInStock": 23
  },
  {
    "Colour": "Bodega Oak",
    "Finish": "Grain",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "12.96",
    "ProductCode": 992984,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E198",
    "QuantityInStock": 27
  },
  {
    "Colour": "Bodega Oak",
    "Finish": "Grain",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "27.5",
    "ProductCode": 992984,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E50",
    "QuantityInStock": 55
  },
  {
    "Colour": "Bodega Oak",
    "Finish": "Grain",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "35",
    "ProductCode": 992984,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E210",
    "QuantityInStock": 70
  },
  {
    "Colour": "Bodega Oak",
    "Finish": "Grain",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "39.5",
    "ProductCode": 992984,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E59",
    "QuantityInStock": 79
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Grain",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "27.5",
    "ProductCode": 992985,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E217",
    "QuantityInStock": 55
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Grain",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "47",
    "ProductCode": 992985,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E29",
    "QuantityInStock": 94
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "20.5",
    "ProductCode": 992990,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E29",
    "QuantityInStock": 41
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "50",
    "ProductCode": 992990,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E179",
    "QuantityInStock": 100
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "100",
    "ProductCode": 992990,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E249",
    "QuantityInStock": 200
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Stipple",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "100",
    "ProductCode": 992990,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E80",
    "QuantityInStock": 200
  },
  {
    "Colour": "Natale Walnut",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "65.4",
    "ProductCode": 992994,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E51",
    "QuantityInStock": 60
  },
  {
    "Colour": "Tassie Oak",
    "Finish": "Gloss",
    "Length": 100,
    "Width": 22,
    "Thickness": 1,
    "price": "41.42",
    "ProductCode": 992995,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E31",
    "QuantityInStock": 38
  },
  {
    "Colour": "Snow Ash",
    "Finish": "Gloss",
    "Length": 25,
    "Width": 22,
    "Thickness": 1,
    "price": "33.75",
    "ProductCode": 993015,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E170",
    "QuantityInStock": 25
  },
  {
    "Colour": "Blue Moon",
    "Finish": "Pearl",
    "Length": 100,
    "Width": 21,
    "Thickness": 1,
    "price": "12.58",
    "ProductCode": 993035,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[3]._id",
    "BayLocation": "E93",
    "QuantityInStock": 37
  },
  {
    "Colour": "White",
    "Finish": "Silk",
    "Length": 25,
    "Width": 22,
    "Thickness": 1,
    "price": "14.85",
    "ProductCode": 993191,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E142",
    "QuantityInStock": 15
  },
  {
    "Colour": "Hushed Pine",
    "Finish": "Flint",
    "Length": 25,
    "Width": 21,
    "Thickness": 1,
    "price": "10.95",
    "ProductCode": 994493,
    "image": "",
    "StockType": "categories[2]._id",
    "Brand": "Brand[4]._id",
    "BayLocation": "E1",
    "QuantityInStock": 15
  }
 ]