[
  {
    "colour": "Chalkstone",
    "finish": "Gloss",
    "length": "2000",
    "width": "650",
    "thickness": "20",
    "price": 131.01,
    "product_code": "979046",
    "BatchNo": " ",
    "image": "https://www.laminex.com.au/medias/p-ES-Chalkstone-RGB-1200x1200-LR.jpg-1200Wx979H?context=bWFzdGVyfGltYWdlc3wzMjQ4MzV8aW1hZ2UvanBlZ3xoMTQvaGU1Lzg4NjY5MjEwNTQyMzgvcF9FU19DaGFsa3N0b25lX1JHQl8xMjAweDEyMDBfTFIuanBnXzEyMDBXeDk3OUh8ZWJmYThmYjdhMjcyZGYzZmNiOWJkNmQ1MzBkNTg2ZjIwMzFiOTc2OGI4MzdkYWZlNGE2NWFjNDhhYTExMTlhMw",
    "StockType": "categories[0]._id",
    "brand": "brand[0]._id",
  },
  {
    "colour": "Grey Glitter",
    "finish": "Gloss",
    "length": "1500",
    "width": "1600",
    "thickness": "20",
    "price": "89.00",
    "product_code": "970263",
    "BatchNo": " ",
    "image": "https://www.qstone.com.au/UploadImages/colour_palette_gallery/5fbb46221fd0f_grey-glitter.jpg",
    "StockType": "categories[0]._id",    
    "brand": "brand[1]._id",    
  },
  {
    "colour": "Snow",
    "finish": "Polished",
    "length": "2850",
    "width": "750",
    "thickness": "20",
    "price": "111.89",
    "product_code": "1214132000",
    "BatchNo": " ",
    "image": "https://www.caesarstone.com.au/Portals/0/Images/Colours/2141.jpg",
    "StockType": "categories[0]._id",
    "brand": "brand[2]._id",           
  },
]